---
os: linux
dist: bionic

language: python
python:
  - "3.7"

services:
  - docker

env:
  global:
    - ROLE_NAME: rancher
  jobs:
    - DISTRO: ubuntu-18.04
    - DISTRO: ubuntu-16.04
    - DISTRO: debian-buster
    - DISTRO: debian-stretch

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y

install:
  - pip3 install molecule docker ansible-lint flake8 testinfra

before_script:
  - cd ../
  - mv lego963-$ROLE_NAME lego963.$ROLE_NAME
  - cd lego963.$ROLE_NAME

script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
