---
language: python
python: "3.7"

services:
  - docker

before_install:
  - sudo apt-get update

install:
  - pip3 install molecule docker ansible-lint

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
