---
language: python

env:
  matrix:
    - DISTRO: ubuntu-18.04
    - DISTRO: debian-buster

install:
  - pip3 install ansible-lint flake8

script:
  - ansible-playbook tests/test.yml -i tests/inventory

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
