---
- name: Update and upgrade apt packages
  apt:
    upgrade: safe
    update_cache: yes

- name: Install curl and pip3
  apt:
    name:
      - curl
      - python3-pip
      - python3-setuptools
      - ufw

- name: Determine if docker is installed
  command: which docker
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Get docker version
  shell: |
    docker --version
    awk '{ print $3 }'
  register: docker_installed_version
  when: docker_installed is success

- name: Install or upgrade docker
  shell: | # noqa 303 305
    curl https://releases.rancher.com/install-docker/{{ docker_version }}.sh
    sh
  warn: false
  when: not docker_installed is success or docker_installed_version.stdout <= docker_version

- name: Upgrade pip
  pip:
    executable: pip3
    name: pip
    state: present

- name: Install additional dependencies
  pip:
    executable: pip3
    name: docker
    state: present

- name: Make sure docker is running
  service:
    name: docker
    state: started
    enabled: true
