---
- name: Install ansible docker dependencies
  pip:
    name: docker
    state: present
    executable: pip3

- name: Pull rancher image
  docker_image:
    name: rancher/rancher:latest
    source: pull

- name: Create rancher image
  docker_container:
    name: rancher
    image: rancher/rancher:latest
    published_ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:8080:8080
    restart_policy: unless-stopped
    detach: yes
    volumes:
      - /host/rancher
      - /var/lib/rancher
