---
- name: Install ufw
  apt:
    name: ufw

- name: Set Ipv6 to `no` in ufw conf
  copy:
    src: ufw
    dest: /etc/default/

- name: Allow 443 and 8080 port for docker run
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "443"
    - "8080"

- name: Reload ufw
  ufw:
    state: enabled

- name: Install ansible docker dependencies
  pip:
    name: docker-py
    state: present
    executable: pip3

- name: Pull rancher image
  docker_image:
    name: rancher/rancher:latest
    source: pull

- name: Create rancher image
  docker_container:
    name: rancher
    image: rancher/rancher:latest
    published_ports:
      - 0.0.0.0:443:443
      - 0.0.0.0:8080:8080
    restart_policy: unless-stopped
    detach: yes
    volumes:
      - /host/rancher
      - /var/lib/rancher

- name: Wait for ports
  wait_for:
    port: "{{ item }}"
    timeout: 100
  loop:
    - 443
    - 8080
  ignore_errors: true
