---
- name: Install ufw
  apt:
    name: ufw

- name: Set Ipv6 to `no` in ufw conf
  copy:
    src: ufw
    dest: /etc/default/

- name: Allow 443 and 8080 port for docker run
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 443
    - 8080

- name: Reload ufw
  ufw:
    state: enabled

- name: Launch rancher on single node
  docker_container:
    name: rancher
    image: rancher/rancher:latest
    restart_policy: unless-stopped
    ports:
      - 8080:8080
      - 443:443

- name: Wait for ports
  wait_for:
    port: "{{ item }}"
    timeout: 100
  loop:
    - 443
    - 8080
  ignore_errors: true
